### ISSUE TITLE
can you please add this to HACS

### ISSUE THREAD

**Issue by DJAMIRSAM** [emcniece/hass-bchydro#11]
I am unable to install this integration and HACS would have made this way easier

**Comment by emcniece** [comment]
I would, if this actually worked. Unfortunately it seems less and less likely that this will ever work - BC Hydro has implemented a captcha on their login page and I haven't had much luck getting past it yet.

I wanted to add this to HACS, and I will if it ever works. For now I think I'll add a deprecation notice to the readme. Apologies.
