### ISSUE TITLE
Error using Sensor

### ISSUE THREAD

**Issue by jdubz666** [emcniece/hass-bchydro#5]
Hi @emcniece, I'm getting the below error when I trying using the BC Hydro Home Assistant Senor. The sensor value is stuck at "Unavailable". My credentials in my Home Assistant Config match the credentials I'm using to log in to the BC Hydro website. I've tried wrapping the credentials in single quotes, double quotes and no quotes, without any luck. Do you have any ideas what's causing this?

Thank you,
Jack

2020-08-10 13:58:17 ERROR (SyncWorker_1) [custom_components.bchydro.sensor] SLID/Account Number parse error: Expecting value: line 1 column 1 (char 0)
2020-08-10 13:58:17 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.latest_usage fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 465, in async_device_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bchydro/sensor.py", line 125, in update
    self._api.login()
  File "/config/custom_components/bchydro/sensor.py", line 182, in login
    json = request.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-08-10 13:58:17 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.consumption_to_date fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 465, in async_device_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bchydro/sensor.py", line 125, in update
    self._api.login()
  File "/config/custom_components/bchydro/sensor.py", line 155, in login
    request = self.call_api(
  File "/config/custom_components/bchydro/sensor.py", line 151, in call_api
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://app.bchydro.com/sso/UI/Login
2020-08-10 13:58:17 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.cost_to_date fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 465, in async_device_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bchydro/sensor.py", line 125, in update
    self._api.login()
  File "/config/custom_components/bchydro/sensor.py", line 155, in login
    request = self.call_api(
  File "/config/custom_components/bchydro/sensor.py", line 151, in call_api
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://app.bchydro.com/sso/UI/Login
2020-08-10 13:58:18 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.next_billing_period fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 465, in async_device_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bchydro/sensor.py", line 125, in update
    self._api.login()
  File "/config/custom_components/bchydro/sensor.py", line 155, in login
    request = self.call_api(
  File "/config/custom_components/bchydro/sensor.py", line 151, in call_api
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://app.bchydro.com/sso/UI/Login

**Comment by emcniece** [comment]
Thanks for the report! Yeah this is something I worked through last night, haven't posted an update yet. The first clue is `SLID/Account Number parse error` - it's not able to get a clean response out of the login redirects. Definitely not an issue with your config.

I'm in the middle of a heavy refactor right now. Got some advice from the HASS core devs on how to prevent spamming the BCHydro website with requests, but implementing `DataUpdateCoordinator` needs an async rewrite.

I'll try and push some updates to a branch tonight so you can peek at the progress, hang in there, I'll post here too once there's a solution.

**Comment by emcniece** [comment]
Hey, I think https://github.com/emcniece/hass-bchydro/pull/6 is ready for testing if you're up to it!

This branch doesn't support `configuration.yaml` entries right now, you'll have to comment those out... but it _does_ have a config flow!

1. Delete all the files you had at `custom_components/bchydro/`
1. Comment out any platform config for this sensor in `configuration.yaml`
1. Fresh copy this repo: `cd custom_components && git clone git clone --single-branch --branch feat/updatecoordinator https://github.com/emcniece/hass-bchydro.git bchydro`
1. Restart HASS
1. Browse to integrations, click + to add new integration, search BCHydro
1. Enter BCHydro email in top field, and password in bottom, click Save
1. ... play with device & sensors?

**Comment by jdubz666** [comment]
Oh wow very cool. 

I followed steps 1-4. I can now add  BCHydro as a new integration but when I add the username and password, press submit. The fields clear and nothing seems to happen. The sensors show as unavailable. I've restarted Hass again to be on the safe side but no luck. 

Also quadruple checked my credentials lol. Any ideas where the issue? Here's the error in the log. 

2020-08-12 23:22:45 ERROR (MainThread) [bchydro.api] Auth error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url=URL('https://app.bchydro.com/BCHCustomerPortal/web/accountsOverview.html')

Thanks alot! @emcniece

**Comment by jdubz666** [comment]
Oh wow very cool.

I followed steps 1-4. I can now add BCHydro as a new integration but when I add the username and password, press submit. The fields clear and nothing seems to happen. The sensors show as unavailable. 

I've restarted Hass again to be on the safe side but no luck. I've cleared all config entries. Also quadruple checked my credentials lol.

 Any ideas where the issue? Here's the error in the log.

2020-08-12 23:22:45 ERROR (MainThread) [bchydro.api] Auth error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url=URL('https://app.bchydro.com/BCHCustomerPortal/web/accountsOverview.html')

Thanks alot! @emcniece

**Comment by emcniece** [comment]
Woah, interesting... thank you for testing. That means the account JSON info we expected wasn't JSON. We should look at the response that comes back and dump it to text.

Unfortunately this just got harder to debug because the BCHydro API now lives over at https://github.com/emcniece/bchydro. I'll make a branch over there with more debugging output, but the spot we need to test is here: https://github.com/emcniece/bchydro/blob/master/bchydro/api.py#L67. Since `response.json()` fails we should log out something like this:

```py
text_res = await response.text() 
print('DUMP START --')
print(text_res)
print('-- DUMP END'
json_res = await response.json()
...
```

Then you can run that API test script as per the README instructions and see what comes out. From what I've seen so far BCHydro returns HTML pages when errors occur, and they don't always have relevant information or status codes.

Do you have any special characters in your password? I wonder if there's a problem transferring strings from the HASS config flow.

Thank you so much for helping to debug this!

**Comment by jdubz666** [comment]
Yea I tried to use the standalone script but I couldn't figure out how to assign the credentials. I'd be happy to get the standalone working first.

In the README section, how do I use

export BCH_USER=your.email@domain.com
export BCH_PASS=your-bch-password

Is that outside of test.py script?

I thought it could be special characters and I changed my password so it was all letters and numbers, no luck doing that.

Happy to help test this and get it working. Thanks for the help.


Jack

**Comment by emcniece** [comment]
You got it - the `export` commands set environment variables. Those are to be executed in your local shell before running `python test.py`. You can run them inline as well, like this:

```sh
BCH_USER=your.email@domain.com BCH_PASS=your-bch-password python test.py
```

Ugh, I just saw that it needs a prerequisite to run:

```sh
pip install beautifulsoup4
BCH_USER=your.email@domain.com BCH_PASS=your-bch-password python test.py
```
I apologize for the mess, this is very quick development. What OS are you working with?

edit: if it's easier you could just edit the test script:

```py
# await a.authenticate(os.environ.get("BCH_USER"), os.environ.get("BCH_PASS"))
await a.authenticate("your.email@domain.com", "your-bch-password")
```

then run like normal:

```sh
python test.py
```

**Comment by jdubz666** [comment]
Ok I'm fine to put them in the script for now. I'm on Debian using another Pi to run it.

Using python3 I get this error

Login failed - unable to find bchydroparam. Are your credentials set?
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "test.py", line 12, in main
    await a.authenticate("*******", "******")
  File "/home/pi/bchydro/bchydro/api.py", line 58, in authenticate
    self._bchydroparam = soup.find(id="bchydroparam").text
AttributeError: 'NoneType' object has no attribute 'text'

Using python I get this 


  File "test.py", line 10
    async def main():
            ^
SyntaxError: invalid syntax

**Comment by jdubz666** [comment]
Maybe I need to upgrade python or something... Correct credentials are here. 

await a.authenticate("your.email@domain.com", "your-bch-password")

**Comment by emcniece** [comment]
Good progress! This package uses `asyncio` which only works with Python3. I bet if you ran `python -V` it would be 2.x.x, while `python3 -V` will be 3.x.x. Stick with `python3 test.py` for now 👍 

The error message is throwing in an anticipated spot. The first line says "unable to find bchydroparam" which is a hidden HTML tag that we expect to find on the page after we log in. If it's missing from the page, we could guess that login didn't work.

It would be useful to inspect the HTML that is missing this `bchydroparam` to see what it says. On line 54 of `api.py` (over here: https://github.com/emcniece/bchydro/blob/master/bchydro/api.py#L54) try appending a print statement:

```py
text = await response.text()
print(text)
```

Then run the test script and browse through that HTML. Clues might be the `<title>` tag, or the start of the `<body>` - sometimes it has a message here about why a request is failing. What do you see?

**Comment by jdubz666** [comment]
Hey! So it spits out a long html file, immediately what I'm spotting is  an alert error "The email or password entered is incorrect. Please try again."

I'm scratching my head with this error haha...  Here's my test.py. No issues with same credentials on the BCHydro website

I can attach full HTML if needed.

```
import os
import asyncio

from bchydro import BCHydroApi

a = BCHydroApi()

async def main():
    await a.authenticate("domain@domain.com", "Password")
    usage = await a.get_daily_usage()
    print(usage.electricity)

    print(a.get_latest_point())
    print(a.get_latest_interval().start, a.get_latest_interval().end)
    print(a.get_latest_usage())
    print(a.get_latest_cost())


asyncio.run(main())
```

**Comment by emcniece** [comment]
Hm... that looks ok, your description of the HTML is clear enough. It really does sound like an auth error.

What login page can you successfully log in at - is it https://app.bchydro.com/sso/UI/Login?realm=bch-ps&goto=https%3A%2F%2Fapp.bchydro.com%3A443%2FBCHCustomerPortal%2Fweb%2Flogin.html ?

**Comment by jdubz666** [comment]
Hey!

I can successfully login following that link.

So that was dumb of me. I realize I made a change to the Api.py and forgot about it. I removed the BCHydro package and reinstalled it. Now I'm getting this error though. I think this is getting better? haha

Auth error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url=URL('https://app.bchydro.com/BCHCustomerPortal/web/accountsOverview.html')
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "test.py", line 13, in main
    usage = await a.get_daily_usage()
  File "/home/pi/bchydro/bchydro/api.py", line 96, in get_daily_usage
    "Slid": self.account.evpSlid,
AttributeError: 'NoneType' object has no attribute 'evpSlid'

**Comment by emcniece** [comment]
PHEW I am so happy to hear this!! 🎉 😆 I was worried that we'd have to chase down some crazy character encoding issue.

Yeah we can work with this next error, that's a good step forward. Looks like the JSON decode fails on https://github.com/emcniece/bchydro/blob/master/bchydro/api.py#L65 which is a good hint that the login didn't return JSON like expected.

I've been working over in https://github.com/emcniece/bchydro tonight - could I ask you to pull a fresh `master` down, then insert a print just before that `response.json()`? Like so:

```py
try:
    response = await session.get(URL_GET_ACCOUNT_JSON)
    print(response.text()) # <-- let's see what actually comes out here
    json_res = await response.json()
```

Don't share the HTML but check for some error or warning messages like before. When this works properly we get account details back, like this:

```json
{
  "accountType": "residential",
  "evpSlid": "0001111111",
  "evpAccount": "000011111111",
  ...
}
```

**Comment by jdubz666** [comment]
Yaaaay getting there!

Did a fresh git clone from there and inserted the print statement. Didn't return any HTML but got this error.

<coroutine object ClientResponse.text at 0x7361a9c0>
/home/pi/bchydro/bchydro/api.py:65: RuntimeWarning: coroutine 'ClientResponse.text' was never awaited
  print(response.text())
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Auth error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url=URL('https://app.bchydro.com/BCHCustomerPortal/web/accountsOverview.html')
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "test.py", line 13, in main
    usage = await a.get_daily_usage()
  File "/home/pi/bchydro/bchydro/api.py", line 97, in get_daily_usage
    "Slid": self.account.evpSlid,
AttributeError: 'NoneType' object has no attribute 'evpSlid'

**Comment by emcniece** [comment]
Ah, apologies, my mistake... still getting used to `asyncio`. "ClientResponse.text' was never awaited" gives it away - the print should be this:

```py
print(await response.text())
```

**Comment by jdubz666** [comment]
Oh nice. 

By the looks of the HTML I'm logged in. This looks like an error at the bottom though.

    $(document).ready(function () {
        $(document).ajaxError(function(event, jqXHR, settings, thrownError) {
            var responseText = jqXHR.responseText;
            var isTimeout = jqXHR.statusText == "timeout";
            if(!jqXHR.getAllResponseHeaders() && !responseText && !isTimeout ){
                // Cross-Origin Request Blocked (e.g.: csr to login)
                location.reload();
            }else{
                if (!!responseText && responseText.indexOf("sso/UI/Login") !== -1){
                    // Verify if it is not html page built from this template and thus contain search string.
                    // Due to poor ajax error hanling could return entire error page.
                    if (responseText.indexOf('responseText.indexOf("sso/UI/Login")') === -1){
                        location.reload();
                    }
                }
            }
        });
        $(document).ajaxSuccess(function(event, jqXHR, ajaxOptions, data) {
            var responseText = jqXHR.responseText;
            if (!!responseText && responseText.indexOf("sso/UI/Login") !== -1){
                // Verify if it is not html page built from this template and thus contain search string.
                // Due to poor ajax error hanling could return entire error page.
                if (responseText.indexOf('responseText.indexOf("sso/UI/Login")') === -1){
                        location.reload();
                }
            }

**Comment by emcniece** [comment]
Alright! Those jQuery responses are queued up and might not fire right away, they could be handlers waiting for a future event. The fact that you're seeing this however does confirm that we're seeing HTML here, and we expected JSON instead.

The URL over in `const.py` is defined as https://app.bchydro.com/evportlet/web/global-data.html. What do you see when you go here while you're logged in? I get a block JSON text.

**Comment by jdubz666** [comment]
Ok Cool!

I also get block JSON text. Account information, etc...

**Comment by emcniece** [comment]
Great progress, we're hot on the trail.

We've narrowed this issue down to this particular HTTP request, and we know it works when you hit it in browser, so there must be an issue when it's accessed in this script. I'm wondering if there are some redirects in here that aren't being followed.

I have to put this down for the night but I'll take a look again tomorrow with fresh eyes. Thank you again so much for helping to debug this, it's super useful having a second tester to confirm changes!

**Comment by jdubz666** [comment]
Alright exciting!

Sounds good man. Have a good night! I'll try and hop on tomorrow.

No problem. Thank you very much for working through it!

Cheers!

**Comment by emcniece** [comment]
Hey @jdubz666 I just pushed a fairly big refactor to https://github.com/emcniece/bchydro/ and https://github.com/emcniece/hass-bchydro/pull/6 is now using `bchydro==0.8.1`.

I think this should finally solve the auth issues! Any chance I could ask you to test it out? 🙏

**Comment by jdubz666** [comment]
Hey @emcniece! Good to hear from you.

Ok I did a fresh git clone, reinstalled everything. Instead of putting the credentials in the test.py, I'll put them in the command this time.

I ran BCH_USER=xxxxxx@xxx.com BCH_PASS=xxxxxxx python3 test.py

I get this error. Happy to help debug this!

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/tenacity/_asyncio.py", line 45, in __call__
    result = await fn(*args, **kwargs)
  File "/home/pi/bchydro/bchydro/api.py", line 186, in refresh
    await self._authenticate()
  File "/home/pi/bchydro/bchydro/api.py", line 136, in _authenticate
    soup = self._validate_html_response(page_html)
  File "/home/pi/bchydro/bchydro/api.py", line 86, in _validate_html_response
    raise BCHydroAlertDialogException(alert_errors.text)
bchydro.exceptions.BCHydroAlertDialogException: 
Select Account
Search for an account above to quickly select and view an account.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/tenacity/_asyncio.py", line 45, in __call__
    result = await fn(*args, **kwargs)
  File "/home/pi/bchydro/bchydro/api.py", line 280, in get_usage
    await self._refresh_if(not self.usage)
  File "/home/pi/bchydro/bchydro/api.py", line 114, in _refresh_if
    await self.refresh()
  File "/home/pi/.local/lib/python3.7/site-packages/tenacity/_asyncio.py", line 79, in async_wrapped
    return await fn(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/tenacity/_asyncio.py", line 42, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/pi/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 373, in iter
    six.raise_from(retry_exc, fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x732eb2f0 state=finished raised BCHydroAlertDialogException>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 16, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "test.py", line 9, in main
    print(await a.get_usage())
  File "/home/pi/.local/lib/python3.7/site-packages/tenacity/_asyncio.py", line 79, in async_wrapped
    return await fn(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/tenacity/_asyncio.py", line 42, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/pi/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 373, in iter
    six.raise_from(retry_exc, fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x728ff310 state=finished raised RetryError>]

**Comment by emcniece** [comment]
Holy smokes. Ok, well the good news is that this error was caught (somewhat) nicely: `BCHydroAlertDialogException` gets raised when the login page shows an alert box message, and in this case the message says "Search for an account...".

The bad news is that I haven't seen this error before 😓 

Do you have access to multiple accounts within your login profile by chance? There was a recent PR to help support this (https://github.com/emcniece/bchydro/pull/2) but I don't have multiple accounts and as such I haven't been able to easily test this scenario.

Lastly, have you created a read-only account before? I'm curious if some read-only credentials works for you... there are some notes at https://github.com/emcniece/bchydro#-read-only-account-sharing.

Thank you so much for your help 🙇

**Comment by jdubz666** [comment]
WOOHOO! Making a linked account solves it.

Thanks for all the work @emcniece  Well done!

**Comment by emcniece** [comment]
🎉 woah, weird... but thank you for confirming!

I think you've landed on a new bug, though it's with the [bchydro](https://github.com/emcniece/bchydro) package and not _this_ repo. I have another user confirming the existence of this mystery dialog, though it's hidden in HTML and not visible. My recent updates that detect this dialog are throwing an error on the hidden dialog, not the visible one,  a false positive.

I've opened https://github.com/emcniece/bchydro/issues/6 and might tap you for a test on your primary account once I get a fix in 🙇

**Comment by jdubz666** [comment]
For sure happy to test with primary account

**Comment by jdubz666** [comment]
Another issue unfortunately... If I uncomment 

  usage = await a.get_usage(hourly=True) 
or
  usage = await a.get_usage(hourly=False)

I get this error. If using the primary account resolves this, I could wait for that instead.

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/tenacity/_asyncio.py", line 45, in __call__
    result = await fn(*args, **kwargs)
TypeError: get_usage() got an unexpected keyword argument 'hourly'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 16, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "test.py", line 8, in main
    usage = await a.get_usage(hourly=True)
  File "/home/pi/.local/lib/python3.7/site-packages/tenacity/_asyncio.py", line 79, in async_wrapped
    return await fn(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/tenacity/_asyncio.py", line 42, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/pi/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 373, in iter
    six.raise_from(retry_exc, fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x76196a70 state=finished raised TypeError>]

**Comment by emcniece** [comment]
Thanks! I was remiss in testing the hourly stats, opening https://github.com/emcniece/bchydro/issues/7 as it's an issue with the API and not the HA integration.

We need to rethink the usefulness of the hourly flag in this integration. It doesn't provide any value for HA unfortunately, since it doesn't provide real-time data. It only provides the hourly points for the previous day.

**Comment by jdubz666** [comment]
No problem.

Personally I think its useful to have the hourly data even even if its not real-time. So I can see which parts of the day are draining. Real time would be way cooler though.

Happy to have the data at all though. Thanks!

**Comment by emcniece** [comment]
Totally agree, it's more useful for sure. I haven't figured out how to do this yet though... maybe we make a new sensor called "Hourly Consumption for Yesterday" or something, then return "real-time" values for the current hour of the previous day?

It's disappointing that we can't get real-time data. I'm trying to get a hold of BCHydro's web team to see if there are any options, no luck yet.

**Comment by jdubz666** [comment]
Fair "most Real time yesterday" doesn't make as much sense for Home Assistant. 

Personally I don't plan on using the Home Assistant sensor (unless its realtime). If possible i'd like to get an hourly JSON extract of the past 24 hours, which I will load into InfluxDB and Grafana separately. 

Yea disappointing for sure. I have a feeling BC Hydro has a reason they don't release it real-time.

**Comment by emcniece** [comment]
Kinda looks like they want to capitalize on it... just found https://www.bchydro.com/powersmart/energy-management-trials/hydrohome-smart-home-trial.html which describes an app with real-time updates.

**Comment by jdubz666** [comment]
I see, I don't see why real-time wouldn't be available then.

Haha a BC Hydro App to control IOT devices is an interesting idea...
